//
// DocsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class DocsAPI {
    /**
     Docs List
     
     - parameter title: (query) Title books 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func searchDocs(title: String, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: DocsList?,_ error: Error?) -> Void)) {
        searchDocsWithRequestBuilder(title: title).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Docs List
     - GET /search.json
     - parameter title: (query) Title books 
     - returns: RequestBuilder<DocsList> 
     */
    open class func searchDocsWithRequestBuilder(title: String) -> RequestBuilder<DocsList> {
        let path = "/search.json"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "title": title.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<DocsList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
