//
// Doc.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Doc: Codable {

    public var authorName: String?
    public var cover: Any?
    public var title: String?
    public var firstPublishYear: Int?
    public var language: [String]?

    public init(authorName: String?, cover: Any?, title: String?, firstPublishYear: Int?, language: [String]?) {
        self.authorName = authorName
        self.cover = cover
        self.title = title
        self.firstPublishYear = firstPublishYear
        self.language = language
    }
	
	public init(from decoder: Decoder) throws {
		
	}

	public func encode(to encoder: Encoder) throws {
		
	}
    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case authorName = "author_name"
        case cover
        case title
        case firstPublishYear = "first_publish_year"
        case language
    }

}
