//
// DocsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct DocsList: Codable {

    public var start: Int?
    public var numFound: Int?
    public var docs: [Doc]?

    public init(start: Int?, numFound: Int?, docs: [Doc]?) {
        self.start = start
        self.numFound = numFound
        self.docs = docs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case start
        case numFound = "num_found"
        case docs
    }

}
